script: "rspec spec"
before_install:
  - rails g has_followers:migration
  - rake db:migrate
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
gemfile:
  - Gemfile
notifications:
  email:
    - fabianoalmeida@gmail.com